config/routes.rb
Rails.application.routes.draw do
  get 'reminder_emails/send_email_reminders'

  root to: 'pages#home'
  get '/invitation_groups/search', to: 'invitation_groups#show_events'
  get '/invitation_groups/confirmation', to: 'invitation_groups#confirmation'
  resources :invitation_groups do
    resources :guests
    resources :invitations
  end
  get 'invitation_groups/:id/edit_invitations', to: 'invitation_groups#edit_invitations', as: 'edit_invitations'
  post 'invitation_groups/:id/edit_invitations', to: 'invitation_groups#update_invitations', as: 'update_invitations'
  get 'pages/non_indian_guide', to: 'pages#non_indian_guide', as: 'non_indian_guide'
  get 'pages/save_the_date', to: 'pages#save_the_date', as: 'save_the_date'
  get 'invitation_groups/show/:code/show_events_already_confirmed', to: 'invitation_groups#show_events_already_confirmed', as: 'show_events_already_confirmed'
  get 'invitation_groups/show/:code/thank_you', to: 'invitation_groups#thank_you', as: 'thank_you'
  get 'invitation_groups/show/:code/guests', to: 'invitation_groups#show', as: 'add_guests'
  get 'invitation_groups/show/:code/events', to: 'invitation_groups#show_events', as: 'link_guests_to_events'
  get 'reminder_emails', to: 'reminder_emails#index', as: 'reminder_emails'
  post 'reminder_emails', to: 'reminder_emails#send_email_reminders', as: 'send_reminder_emails'
end

app/controllers/invitation_groups_controller.rb
class InvitationGroupsController < ApplicationController
  before_action :set_invitation_group, only: [:edit, :update, :destroy, :show_events_already_confirmed]


  def show_events_already_confirmed
    @event_to_attending_hash = Event.all.collect { |event|
      attending_guests = Guest.joins(:invitations).where(invitations: {event_id: event.id, invitation_group_id: @invitation_group.id, is_accepted: true})
      [event, attending_guests]
    }.to_h
  end

  def show_events
    code = params[:code].strip
    @invitation_group = InvitationGroup.find_by_code code.upcase
    if @invitation_group.nil?
      flash[:danger] = "You have entered the invalid RSVP code: \"#{code}\".  If you believe that you have received this message in error, please contact us via palakandjared@gmail.com, or call Veena at 678-232-4506."
      redirect_to "#{root_path}#rsvp"
    else
      if can_change_rsvp_answers?
        render 'show_events'
      else
        redirect_to action: :show_events_already_confirmed, code: @invitation_group.code
      end
    end
  end


  def edit_invitations
    authenticate_admin!
    id = params[:id]
    @invitation_group = InvitationGroup.find id
  end

  # ToDo make this better.  Is kind of hacky. Seems like there should be a more "rails" way of doing this.
  # Unable to add temp invitations for view to manipulate.
  # Rails automatically saves the invitations when adding them to the collection of invitations.
  def update_invitations
    authenticate_admin!
    ig = InvitationGroup.find params[:id]
    saved_keys = ig.invitations.collect { |inv|
      [view_context.generate_key(event: inv.event, guest: inv.guest), true]
    }.to_h

    # Add needed invitations
    params[:event_to_guests].each { |relation_str, val|
      if saved_keys[relation_str]
        # we're good
      else
        # Need to add one
        event, guest = view_context.extract_event_and_guest(relation_str)
        ig.invitations.build(event: event, guest: guest).save!
      end
    }

    # Remove old invitations
    saved_keys.each { |relation_str, val|
      if params[:event_to_guests][relation_str]
        # in both, good
      else
        # shouldn't be saved
        event, guest = view_context.extract_event_and_guest(relation_str)
        invitations = Invitation.where(event: event, guest: guest, invitation_group: ig)
        raise "more than one found" if invitations.size > 1
        Invitation.destroy(invitations.first.id)
      end
    }
    flash[:success] = 'Successfully updated invitation group!'
    redirect_to action: 'index'
  end

  # POST /invitation_groups
  # POST /invitation_groups.json
  def create
    authenticate_admin!
    @invitation_group = InvitationGroup.new(params.require(:invitation_group).permit(:code))
    respond_to do |format|
      if @invitation_group.save
        format.html { redirect_to action: "index", code: @invitation_group.code, notice: 'Invitation group was successfully created.' }
        format.json { render :show, status: :created, location: @invitation_group }
      else
        format.html { render :new }
        format.json { render json: @invitation_group.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    authenticate_admin!
    @invitation_groups = InvitationGroup.all
    @new_invitation_group = InvitationGroup.new(is_confirmed: false, code: InvitationGroup.generate_random_code)
  end

  def confirmation
    code = params[:code]
    @invitation_group = InvitationGroup.find_by_code code
    @invitation_group.is_confirmed = true
  end

  def thank_you
    code = params[:code]
    @invitation_group = InvitationGroup.find_by_code code
  end

  # PATCH/PUT /invitation_groups/1
  # PATCH/PUT /invitation_groups/1.json
  def update

    if can_change_rsvp_answers?
      respond_to do |format|
        if @invitation_group.update(invitation_group_params)
          if @invitation_group.is_confirmed
            format.html { redirect_to action: "thank_you", code: @invitation_group.code, notice: 'Invitation group was successfully updated.' }
          else
            format.html { redirect_to action: "confirmation", code: @invitation_group.code, notice: 'Invitation group was successfully updated.' }
          end
          format.json { render :show, status: :ok, location: @invitation_group }
        else
          format.html { render :edit }
          format.json { render json: @invitation_group.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to 'invitation_groups#show_events_already_confirmed', code: @invitation_group.code
    end
  end

  private

  def can_change_rsvp_answers?
    !@invitation_group.is_confirmed || admin_signed_in?
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_invitation_group
    id = params[:id]
    code = params[:code]
    if id
      @invitation_group = InvitationGroup.find(params[:id])
    elsif code
      @invitation_group = InvitationGroup.find_by_code code.strip.upcase
    end
  end


  def invitation_group_params
=begin
    {
        "invitations_attributes" => {"0" => {"is_accepted" => "1", "id" => "30"},
                                     "1" => {"is_accepted" => "0", "id" => "31"}
        }
    }
=end
    inv_grp_params = params["invitation_group"]
    res= params.permit(:invitation_group, :code).tap do |whitelisted|
      is_confirmed = inv_grp_params["is_confirmed"]
      if is_confirmed
        whitelisted[:is_confirmed] = is_confirmed
      end

      invi_attrs = inv_grp_params["invitations_attributes"]
      if invi_attrs
        whitelisted[:invitations_attributes] = invi_attrs
      end
    end
    res
  end
end

app/helpers/invitation_groups_helper.rb
module InvitationGroupsHelper
  include ApplicationHelper

  def print_attending(invitations)
    guests = invitations.select(&:is_accepted).collect(&:guest).collect(&:full_name).join(", ")
    guests.empty? ? 'none' : guests
  end

  def generate_key(event:, guest:)
    "#{guest.id}-#{event.id}"
  end

  def extract_event_and_guest(key)
    out= key.split('-')
    guest_id = out.first
    event_id = out.last
    [Event.find(event_id), Guest.find(guest_id)]
  end

end

app/views/invitation_groups/_already_received_rsvp.html.erb
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="alert alert-info">
            We have already received your RSVP. Please contact palakandjared@gmail.com, or call Veena at 678-232-4506
            with any questions.
        </div>
    </div>
    <div class="col-md-2"></div>

</div>
<div class="container">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-9">
            <p>Guests currently RSVPed to attend: </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <%= render partial: "shared/accepted_table", locals: {event_to_attending_hash: @event_to_attending_hash} %>
        </div>
    </div>
</div>

app/views/invitation_groups/_select_accepted_invitations_form.html.erb
<div class="row no-list-style padding-bottom-20">
    <div class="col-md-1"></div>
    <div class="col-md-11">
        <div>
            Please select which guests will be attending each event.
        </div>
        <%= semantic_form_for @invitation_group do |f| %>

            <% last_event = nil %>
            <%= f.semantic_fields_for :invitations, @invitation_group.invitations_sorted_by_event do |invitation| %>
                <% event = invitation.object.event %>
                <h1 class="myheading">
                    <%= "#{event.name} - #{event.time.strftime("%A %B %d, %Y ")}" unless event == last_event %>
                    <% last_event = event %>
                </h1>

                <div class="names">
                    <%= invitation.input :is_accepted, label: invitation.object.guest.full_name %>
                </div>
            <% end %>

            <%= f.action :submit, :label => "Save Guest Selections", :button_html => {:id => 'submitSaveGuestSelections', :class => "red-on-gold btn"} %>
        <% end %>
    </div>
</div>

app/views/invitation_groups/_show_events_layout.html.erb
<div id="eventsSelectionPage" class="yellow-on-pink content-section">
    <div class="lavReg row hugeText padding-bottom-20">
        RSV P
    </div>
    <%= yield %>
</div>

app/views/invitation_groups/confirmation.html.erb
<div id="confirmationPage" class="yellow-on-pink content-section">
    <div class="lavReg row hugeText padding-bottom-20">
        Confirmation
    </div>

    <div class="row no-list-style padding-bottom-20">
        <div class="col-md-1"></div>
        <div class="col-md-11">
            <div>
                You have indicated the following:
            </div>
            <ul>
                <div class="padding-top-20 padding-bottom-20">
                    <% @invitation_group.invitations.group_by(&:event).each { |key, values| %>

                        <li>
                            <b> <%= "#{key.name}:" %>  </b>
                            <%= "#{print_attending values} attending" %>
                        </li>
                    <% } %>
                </div>
            </ul>
            <div>
                Is this correct?
            </div>


            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-1">
                        <%= link_to 'Back', link_guests_to_events_path(:code => @invitation_group.code), {class: 'btn red-on-gold'} %>
                    </div>
                    <div class="col-md-1">
                        <%= semantic_form_for @invitation_group do |f| %>
                            <%= f.input :is_confirmed, :as => :hidden %>
                            <%= f.action :submit, :label => "Confirm", :button_html => {:id => 'confirmRsvp', :class => "red-on-gold btn"} %>
                        <% end %>
                    </div>
                </div>
            </div>


            <div>
                Your RSVP will not be received until you click "Confirm"
            </div>

        </div>
    </div>
</div>

app/views/invitation_groups/edit_invitations.html.erb
<div class="black-on-white">

    <div class="lavReg row hugeText padding-bottom-20">
        Edit Invitations
    </div>
    <div class=" container">

        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-7">
                <div id="eventsSelectionPage">
                    <% if @invitation_group.is_confirmed %>
                        <div class="btn-danger">
                            This invitation group has already been confirmed, so editing it isn't recommmended!
                        </div>
                    <% end %>
                    <%= form_tag do %>
                        <table>
                            <tr>
                                <td>Guest</td>
                                <td>Invited?</td>
                                <td>Event</td>
                            </tr>
                            <% selected_bxs = {}
                               @invitation_group.invitations.each { |inv|
                                 selected_bxs[generate_key(guest: inv.guest, event: inv.event)] = true
                               } %>
                            <% @invitation_group.guests.each { |guest| %>
                                <% Event.all.each { |event| %>
                                    <tr>
                                        <td><%= link_to(guest.full_name, edit_invitation_group_guest_url(@invitation_group.id, guest.id)) %></td>
                                        <% key = generate_key(guest: guest, event: event) %>
                                        <td><%= check_box_tag("event_to_guests[#{key}]", 1, selected_bxs[key]) %></td>
                                        <td><%= event.name %></td>
                                    </tr>
                                <% } %>
                            <% } %>
                        </table>
                        <%= submit_tag("Save") %>
                    <% end %>
                    <div class="padding-top-20 padding-bottom-20">
                        <div>Assocated Guests</div>
                        <% @invitation_group.associated_guests.each do |guest| %>
                            <div><%= guest.full_name %></div>
                        <% end %>
                        <%= link_to 'Create Guest', new_invitation_group_guest_path(@invitation_group.id) %>

                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <%= link_to 'Back to RSVP list', invitation_groups_path %>
            </div>
            <div class="col-md-1"></div>
            <div class="col-md-2    ">
            </div>

        </div>
    </div>
</div>

app/views/invitation_groups/index.html.erb
<div class="red-on-gold">
    <div class="padding-top-20">
        <h3>Total Invitation Group Count: <%= InvitationGroup.count %></h3>

        <h3>Total Finalized Invitation Group Count: <%= InvitationGroup.where(is_confirmed: true).count %></h3>
    </div>
    <table>
        <thead>
        <td>
            All Names in Invitation Group
        </td>
        <td>
            RSVP Code
        </td>
        <td>Last Mod Date</td>
        <td>Is Finalized</td>
        <% event_toc_count_map = {} %>
        <% Event.all.each { |eve| %>
            <% event_toc_count_map[eve.name] = 0 %>
            <td>
                <%= eve.name %>
            </td>
        <% } %>


        </thead>
        <% @invitation_groups.each { |inv| %>
            <tr>
                <td>
                    <%names = inv.guest_names %>
                    <%names = 'empty' if names.empty? %>
                    <%= link_to names, edit_invitations_path(inv) %>
                </td>
                <td>
                    <%= link_to inv.code, link_guests_to_events_url(inv.code) %>
                </td>
                <td>
                    <%= inv.updated_at %>
                </td>
                <td>
                    <%= inv.is_confirmed %>
                </td>
                <% Event.all.each { |eve| %>
                    <td>
                        <%= accepted_attends = inv.accepted_attends_for(eve)
                            event_toc_count_map[eve.name] += accepted_attends.size
                            accepted_attends.collect { |g| g.full_name }.join ',' %>
                    </td>
                <% } %>
            </tr>
        <% } %>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>
                Total
            </td>
            <% Event.all.each { |eve| %>
                <td>
                    <%= event_toc_count_map[eve.name] %>
                </td>
            <% } %>
        </tr>
    </table>
    <%= form_for @new_invitation_group, url: { action: "create" } do |f| %>
        <div>
            <%= f.hidden_field :code%>
            <%= f.submit "Create new Invtation Group" %>
        </div>
    <% end %>
</div>

app/views/invitation_groups/show_events.html.erb
<%= render partial: "select_accepted_invitations_form", layout: "show_events_layout" %>

app/views/invitation_groups/show_events_already_confirmed.html.erb
<%= render partial: "already_received_rsvp", layout: "show_events_layout" %>

app/views/invitation_groups/thank_you.html.erb
<div id="thankYouPage" class="yellow-on-pink stretch-vertical content-section">
    <div class="lavReg row hugeText padding-bottom-20">
        Thank You
    </div>

    <div class="center-text padding-bottom-20">

        <% if @invitation_group.has_attendees %>
            <h2>
                We look forward to celebrating with you!
            </h2>
        <% else %>
            <h2>
                We're sorry to miss you!
            </h2>
        <% end %>

    </div>
</div>