config/routes.rb
Rails.application.routes.draw do
  get 'reminder_emails/send_email_reminders'

  root to: 'pages#home'
  get '/invitation_groups/search', to: 'invitation_groups#show_events'
  get '/invitation_groups/confirmation', to: 'invitation_groups#confirmation'
  resources :invitation_groups do
    resources :guests
    resources :invitations
  end
  get 'invitation_groups/:id/edit_invitations', to: 'invitation_groups#edit_invitations', as: 'edit_invitations'
  post 'invitation_groups/:id/edit_invitations', to: 'invitation_groups#update_invitations', as: 'update_invitations'
  get 'pages/non_indian_guide', to: 'pages#non_indian_guide', as: 'non_indian_guide'
  get 'pages/save_the_date', to: 'pages#save_the_date', as: 'save_the_date'
  get 'invitation_groups/show/:code/show_events_already_confirmed', to: 'invitation_groups#show_events_already_confirmed', as: 'show_events_already_confirmed'
  get 'invitation_groups/show/:code/thank_you', to: 'invitation_groups#thank_you', as: 'thank_you'
  get 'invitation_groups/show/:code/guests', to: 'invitation_groups#show', as: 'add_guests'
  get 'invitation_groups/show/:code/events', to: 'invitation_groups#show_events', as: 'link_guests_to_events'
  get 'reminder_emails', to: 'reminder_emails#index', as: 'reminder_emails'
  post 'reminder_emails', to: 'reminder_emails#send_email_reminders', as: 'send_reminder_emails'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="no-padding alert alert-<%= name.to_s == 'notice' || name.to_s == 'success' ? 'success' : 'danger' %>   ">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-default">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><%= link_to 'Home', root_path%></li>
                        <li><%= link_to 'Save the Date Game', page_path('save_the_date') %></li>
                        <li><%= link_to 'A Non Indian\'s Guide to a Hindu Wedding', page_path('non_indian_guide') %></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin
                                <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><%= link_to 'Invitation Groups', invitation_groups_path %></li>
                                <li><%= link_to 'Reminder Emails', reminder_emails_path %></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container-fluid -->
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Palak & Jared" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Palak & Jared" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
</head>
<body>
<header>
    <div id="headContainer" class="container-fluid affix up-top-max">
        <div class="row ">
            <%= render 'layouts/messages' %>
        </div>
    </div>

    <%= render 'layouts/navigation' %>
</header>
<main role="main">
    <%= yield %>
</main>
</body>
</html>